# Generated by Django 5.2.4 on 2025-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultlink',
            name='original_link',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='defaultlink',
            name='shortlink',
            field=models.CharField(max_length=50),
        ),
    ]
